language: python
python:
- '3.4'
- '3.6'
matrix:
  include:
    - language: generic
      os: osx
      before_install:
        - brew update
        - brew install python3
        - virtualenv env -p python3
        - source env/bin/activate
before_install:
- if [ "$$TRAVIS_OS_NAME" = "linux" ] ; then sudo apt-get update -q ; fi
- if [ "$$TRAVIS_OS_NAME" = "linux" ] ; sudo apt-get install libasound2-dev -y ; fi
install:
- pip install setuptools python-rtmidi --upgrade
- if [ "$TRAVIS_PYTHON_VERSION" = "3.6" ] ; then pip install cx_Freeze==6.0b1 --upgrade ; fi
script:
- utils/check_version.py
- python setup.py build test
- python setup.py sdist bdist_wheel
- export BUILD_VER=${TRAVIS_TAG:-b${TRAVIS_BUILD_NUMBER}}
- if [ "$TRAVIS_PYTHON_VERSION" = "3.6" ] ; then
  python setup.py build_exe --build-exe dist/chord_exercise_partner-linux-x64-${BUILD_VER} ;
  cd dist ; tar czvf chord_exercise_partner-linux-x64-${BUILD_VER}.tar.gz chord_exercise_partner-linux-x64-${BUILD_VER}; cd .. ;
  fi
deploy:
  provider: releases
  api_key:
    secure: hqEiLfvldYlPSneu+f5SkqF/XNxIvT/aRnN0+ujDLALKl2ko59yu7qjKuJdzQtTyfLI6jYULXBQx9LWkTSljC8gzuWmLrnt0PhGhegPzriCjwpYtm4sS5tobAldiC1MxH8oTH1rKqdL5PAbDhCVQSucyBbdjkIQ4v98cWiLoNdpRBLGMpazTqXxviCZI1qOtZM9BhcOpardAAVzud/hxErDvJID6omUGMxnaWJ8NeFBQ349ukUwvn6Scf6vEfHNV39TprTPhTnW62KM+cXU+dFyZGT52cdJZR0PeWXKmQxjhoO1IFnwlAuYnMKHXqlMRkTdZK2qgJq8e1/6EbyiQHQZkkrwY8Y6D+pkLHWO9GbglUzzgnQORTTCl5nK6xnzgFxnwhIc+mmDVCEWbUidC9ObN2seyXvIG9xpl2i8tdJJLeVOXTliTk7KxT8ZOdseKM2PJK6lo1KrIjo6TGiTbSyZGc7LDvZtVYCevXIXrszIuoLz20jAyw0zox/TRejjlUJtW5nm6Nm0WWCzML+bZ9P78W9TsQDmbik/q9RRVCfLVxR52xEbyltOgGLKvPXlRTvOQb3Atb70L8bGSfcLhWRVYsXzFsnda5AJoV/1oSOEZOreuoDUBaH2Sm/ul08Ec/+8UNjbz1hgs910tviRZYb/VJ1dcEl1XMKBJYqcxo88=
  file_glob: true
  file: dist/chord_exercise_partner-linux-*.tar.gz
  draft: true
  tag_name: ${TRAVIS_TAG}
  name: ${TRAVIS_TAG}
  skip_cleanup: true
  on:
    repo: Jajcus/chord_exercise_partner
    tags: true
    branch: master
    condition: $TRAVIS_PYTHON_VERSION == 3.6
