language: python
python:
    - "3.4"
    - "3.6"
before_install:
    - sudo apt-get update -q
    - sudo apt-get install libasound2-dev -y
install:
    - pip install setuptools python-rtmidi cx_Freeze --upgrade
script:
    - python setup.py build test
    - python setup.py sdist bdist_wheel
    - python setup.py build_exe --build-exe chord_exercise_partner-linux-x64-${TRAVIS_TAG:-b${TRAVIS_BUILD_NUMBER}}
    - tar czvf chord_exercise_partner-linux-x64-${TRAVIS_TAG:-b${TRAVIS_BUILD_NUMBER}}.tar.gz chord_exercise_partner-linux-x64-${TRAVIS_TAG:-b${TRAVIS_BUILD_NUMBER}}

# vi: sts=4 sw=4 et
