version: 0.3.{build}
environment:
  matrix:
  - PYTHON_VERSION: 3.4
    PYTHON: C:\Python34\Python
  - PYTHON_VERSION: 3.6
    PYTHON: C:\Python36\Python
install:
- cmd: >-
    %PYTHON% -m ensurepip --upgrade

    %PYTHON% -m pip install setuptools python-rtmidi pynsist --upgrade
build_script:
- cmd: >-
    %PYTHON% utils/check_version.py

    %PYTHON% setup.py build test sdist

    %PYTHON% -m chord_exercise_partner.timing

    IF %PYTHON_VERSION% == 3.6 %PYTHON% -m nsist installer.cfg
artifacts:
- path: build\nsis\Chords_Exercise_Partner_*.exe
  name: Windows installer
- path: dist\jajcus.chord_exercise_partner-*.tar.gz
  name: sdist
- path: dist\jajcus.chord_exercise_partner-*.whl
  name: wheel
