version: 0.3.{build}
environment:
  matrix:
  - PYTHON_VERSION: 3.4
    PYTHON: C:\Python34\Python
  - PYTHON_VERSION: 3.6
    PYTHON: C:\Python36\Python
install:
- cmd: >-
    %PYTHON% -m ensurepip --upgrade

    %PYTHON% -m pip install setuptools python-rtmidi pynsist --upgrade
build_script:
- cmd: >-
    %PYTHON% utils/check_version.py

    %PYTHON% setup.py build test sdist

    %PYTHON% -m chord_exercise_partner.timing

    IF %PYTHON_VERSION% == 3.6 %PYTHON% -m nsist installer.cfg

    IF %PYTHON_VERSION% == 3.6 %PYTHON% setup.py bdist_msi
artifacts:
- path: build\nsis\chords_exercise_partner-*.exe
  name: exe
- path: dist\jajcus.chord_exercise_partner-*.tar.gz
  name: sdist
- path: dist\jajcus.chord_exercise_partner-*.whl
  name: wheel
deploy:
  description: '$(appveyor_build_version) release'
  provider: GitHub
  auth_token:
    secure: Zx/t/QC8IU3f1wHGwhnuDKHhBOvab3dB4TKP/rr4v4pQ11g6JGIvmpXj3nx9tIt3
  artifact: exe
  draft: true
  prerelease: true
  force_update: true
  on:
    branch: master
    appveyor_repo_tag: true
